apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - name: code-server
          image: lscr.io/linuxserver/code-server:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8443
          env:
            - name: TZ
              value: Europe/Berlin
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: SUDO_PASSWORD
              value: ihavethepower
          volumeMounts:
            - mountPath: /config-files
              name: config-files
            - mountPath: /sample-in-root.txt
              name: config-files
              subPath: other-sample.txt
      volumes:
        - name: config-files
          configMap:
            name: code-server-config-files
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
spec:
  type: NodePort
  selector:
    app: code-server
  ports:
  - port: 8443
    targetPort: 8443
    nodePort: 30443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-config-files
data:
  sample.txt: |
    this is just a sample file

  other-sample.txt: |
    this is another sample file which will be mounted additional through subPath
